global:
  scrape_interval: 5s  # Set the scrape interval to 5 seconds

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'python_app'
    static_configs:
      - targets: ['localhost:8000']